### ISSUE TITLE
Weak password policy (Team 2)

### ISSUE THREAD

**Issue by safaa-hamdy** [ELG7186-s22/project-group-4#42]
When trying to register with multiple accounts we found that you didn’t implement any password policy. Currently, your policy accepts password with 16 or more characters and with only one requirement which is at least one character has to be small cased. This policy is too weak and can’t be a one to count on.
You should implement a password policy to accept passwords with a mix of small, capital letters, numbers and some special listed characters. Such a weak policy is subject to many possible attacks.

**Comment by MagicianMido32** [comment]
Fixed it thank you !
https://www.codegrepper.com/code-examples/javascript/strong+password+validation+nodejs
