### ISSUE TITLE
System crashes when uploading a file (Team 3) 

### ISSUE THREAD

**Issue by norantharowat** [ELG7186-s22/project-group-4#44]
When trying to upload a file of any extension whether it is a Jason file or not the website crashes as shown.
 

![image](https://user-images.githubusercontent.com/43759597/182615962-43679a7a-85de-40c5-90e4-a9d29c668169.png)

**Comment by MagicianMido32** [comment]
please test on the deployed version on heruko, as your configurations (in your own pc) is different

**Comment by norantharowat** [comment]
Sorry, but the deployed version should be the same as the codes in the repository.
They should act the same, it is not a PC problem.

**Comment by MagicianMido32** [comment]
it's working on my pc locally and it's working on the deployed version
