### ISSUE TITLE
Missing authorization (Team 3) 

### ISSUE THREAD

**Issue by norantharowat** [ELG7186-s22/project-group-4#45]
I am logged in as a normal user as shown, not an admin user.

![image](https://user-images.githubusercontent.com/43759597/182622406-34c76f08-32a3-48f4-9868-4f170ed5be94.png)

But here I can access the edit config path, which is supposed to be a restricted area for admins only.

![image](https://user-images.githubusercontent.com/43759597/182623079-c0a74112-ad8b-4c19-a96e-3af64d3c9f4f.png)

Reason:

Wrong if condition, you should have brackets around the equal sign operation then negate the result. 

![image](https://user-images.githubusercontent.com/43759597/182624363-51a6771d-d22b-4844-82d4-4273ad9d7ad3.png)

To recreate this issue, just login as a normal user and then type in the address bar:
http://localhost:8081/editconfig

you will be redirected to the following page:
http://localhost:8081/public/edit_cfg.html

**Comment by MagicianMido32** [comment]
issue fixed, test on the deployed version

**Comment by norantharowat** [comment]
Sorry, but the deployed version should be the same as the codes in the repository.
They should act the same.

**Comment by MagicianMido32** [comment]
latest update included a fix for this vulnerability, it was pushed to the deployment repository however and we didn't notice it until now. that's why you couldn't reproduced it on the deployed version.
Fixed it.
