### ISSUE TITLE
Broken disable solutions functionality (Team 3)

### ISSUE THREAD

**Issue by norantharowat** [ELG7186-s22/project-group-4#47]
When I added a new challenge to be disabled in the config file, like the second challenge in the yellow belt as shown.

![image](https://user-images.githubusercontent.com/43759597/182793670-235728c1-521d-4265-9bdf-5505f8ee71c1.png)

And then uploading the config file, it says that it was successfully uploaded, but when I log in as a normal student I still can access the show solution button.

![image](https://user-images.githubusercontent.com/43759597/182793996-99b1c088-c099-4c5e-a767-4f0cdd5016e0.png)

**Comment by MagicianMido32** [comment]
actually we have tested it many times and are sure it's working 100%, but I took it on myself to tested again, and again it's working as expected. check your browser cache, it has cached the page.
