### ISSUE TITLE
Weak Ciphers Enabled (Team2)

### ISSUE THREAD

**Issue by capmaro** [ELG7186-s22/project-group-4#50]
Dears,
You should allow only strong ciphers on your web server to protect secure communication with your visitors.

"Impact"
Attackers might decrypt SSL traffic between your server and your visitors.

"Vulnerabilities"
https://hellsgate32.herokuapp.com
   Request:
      [HUNTER] SSL Connection
   Response:
     Response Time (ms) : 1 Total Bytes Received : 27 Body Length : 0 Is Compressed : No

**Remediation**
Configure your web server to disallow using weak ciphers.

"External References"
OWASP - Insecure Configuration Management
OWASP Top 10-2017 A3-Sensitive Data Exposure
Zombie Poodle - Golden Doodle (CBC)
Mozilla SSL Configuration Generator
Strong Ciphers for Apache, Nginx and Lighttpd

**Comment by MagicianMido32** [comment]
can you reproduce this, e.g. decrypt the traffic between the client and the server. this issue makes no sense.
